name: swiss_knife_application
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  path: ^1.8.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  validators: ^3.0.0
  logging: ^1.2.0
  file_selector: ^1.0.1
  jni: ^0.7.0
  pdfbox_plugin:
    path: ./pdfbox_plugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  jnigen: ^0.7.0
  msix: ^3.16.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

msix_config:
  display_name: "Swiss knife of apps"
  publisher_display_name: Divine bug
  identity_name: dev.bugdivine.swissknife
  msix_version: 1.0.0.0
  languages: en-us, de-de
  capabilities: ""
  app_installer: #<-- app installer configuration
    publish_folder_path: C:\Users\sj307\Desktop\GitHub\
    hours_between_update_checks: 0
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: false